doc/quickstart.rst
flask_restplus/api.py

Docs update related to #6 and #7

Docs update

---

flask_restplus/api.py
tests/test_api.py

#22 optional specs endpoint addition

---

flask_restplus/swagger.py
tests/__init__.py
tests/test_apidoc.py
tests/test_swagger_utils.py
tests/test_utils.py

#27 support for python 2.6

---

doc/quickstart.rst

I'm not sure, but is this a typo?

possible typo

---

doc/documenting.rst

Corrected spelling of several words

Fix typos in documenting.rst

---

flask_restplus/swagger.py
tests/test_swagger_utils.py

This is very similar to #64 except it is for lists instead of choices.

Use proper 'collectionFormat' for reqparse lists

---

flask_restplus/api.py
tests/test_errors.py

The order of error handling in handle_error() prevented the ability to
have custom error handling for an exception inheriting from Werkzeug's
base HTTPException class. Tweaked the order slightly to make it
possible to handle these exceptions using the custom error handling
methods that were already built-in should someone want to.

Add ability to handle Werkzeug HTTPException

---

flask_restplus/resource.py
tests/test_swagger.py

Fix resource and method documentation hiding when doing @api.hide or
@api.doc(False).

Fix resource doc hiding

---

flask_restplus/api.py
tests/test_apidoc.py

Change root endpoint url to prefix if there is one

---

flask_restplus/api.py
tests/test_errors.py

Fix namespace error handlers (fixes #141)

---

flask_restplus/fields.py

Fix tpyo in exclusiveMinimum

---

flask_restplus/resource.py
tests/test_payload.py

Changes:
* Modify the `resource.Resource.validate_payload` method to support validation for a collection of objects of a resource.
* Add unit tests in `test_payload.PayloadTestCase`
Resolves issue #230.

Add validation for lists in the expect decorator

---

flask_restplus/__init__.py

Fix from flask_restplus import *

---

flask_restplus/swagger.py
tests/test_swagger.py

Ref https://github.com/noirbizarre/flask-restplus/pull/263

Add test case for float for flask-restplus/pull/263

---

flask_restplus/representations.py

Ujson is fast C implementation of json:loads/dumps.
It is simple way to speed up marshaling.

Use ujson when available.

---

CHANGELOG.rst
doc/scaling.rst

While reading the docs, encountered a couple of errors.  Thought I'd submit fixes to the docs.

added formatting, removed typos. updated change log.wq

---

doc/parsing.rst

Fix small typo in parsing.rst.

---

doc/quickstart.rst

of lazily with the factory pattern  --> or lazily with the factory pattern

Fixed typo in quickstart.rst

---

flask_restplus/__init__.py

Add 'Namespace' to export list

---

CHANGELOG.rst
flask_restplus/api.py
tests/test_api.py

Fix Namespace decorators

---

doc/swagger.rst
flask_restplus/swagger.py
tests/test_postman.py
tests/test_swagger.py

Don't include namespaces without resources to the SWAGGER documentation

---

.travis.yml
requirements/develop.pip
setup.py

Great, my first PR into this and there's a typo in the log. How much do we care? Lemma know and I'll rebase and clean up the entry

617 add extra dev and change requirements file to work wiht extras_require

---

CHANGELOG.rst
doc/swagger.rst
requirements/doc.pip
setup.py

- update Changelog
- update build doc requirements (allows to use the [sphinx-issues'](https://github.com/sloria/sphinx-issues) `:pr:`  extension)

update build doc requirements

---

README.rst

Let's inform the community about the current *maintainers* of the project.

add a note about the project maintenance

---

requirements/test.pip

Replace pytest-faker requirement for Faker.

---

doc/scaling.rst

fix typo in scaling.rst

---

.github/ISSUE_TEMPLATE/bug-report.md

Per the discussion in issue #689, please provide feedback on guidance on other template types (help/support, new feature/enhancement)

Issue template for bugs/defects

---

.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md

Pull request template

---

CHANGELOG.rst
flask_restplus/namespace.py
flask_restplus/swagger.py
tests/conftest.py
tests/test_swagger.py

This is my proposed fix for issue #661. My approach is to convert the response code to string before it is merged onto the Swagger dictionary.

Fix for issue #661

---

doc/marshalling.rst
doc/parsing.rst
doc/swagger.rst
flask_restplus/api.py
flask_restplus/errors.py
flask_restplus/mask.py
flask_restplus/model.py
flask_restplus/namespace.py

Fixed several comment and readme typos.

Fix some typos
