noirbizarre/flask-restplus

flask_restplus/swagger.py

I made couple more changes so the API paths in the Swagger Docs UI are sorted nicely by the endpoint instead of being randomly ordered. Seems like a a better default

Made changes to sort API paths in Swagger

---

flask_restplus/reqparse.py
tests/test_reqparse.py

Passthrough positional arguments of RequestParser constructor (fix #47)

---

flask_restplus/swagger.py
tests/test_swagger_utils.py

The swagger spec allows for multiple different collection formats to be
specified. By default csv (comma delimited) is used but this does not
work well with reqparses way of working which is multi in the swagger
spec (foo=bar&foo=baz).

Use proper 'collectionFormat' for reqparse choices

---

doc/documenting.rst

I could be wrong about this example being incorrect but judging from the other parts of the documentation about the security stuff this seems right.

Fix incorrect example

---

flask_restplus/api.py
flask_restplus/resource.py

In 0da4f64b2, JSON validation was introduced. In order to acheive this a
validate_payload() decorator was getting added to every Resource(). The
problem was because Resource() was getting instantiated new every time
it would just continue to add this method over and over until eventually
Python would die due to a maximum recursion error.
By moving the validate_payload() method to the Api() class it resolves
the issue of a new version of the method being added to each Resource().
In order to keep the ability of being able to easily change/override the
validate_payload() method a _add_validate_payload() method was added to
the Resource() init method where an end user can easily manipulate the
workflow in any subclasses.

Fix maximum recursion error (fixes #80)

---

flask_restplus/swagger.py

This should keep the order of parameters when doing something like:
```
parser.add_argument('first_example', type=str)
parser.add_argument('second_example', type=str)
parser.add_argument('third_example', type=str)
```
Not ordered:
Ordered:

Keep order in parameters.

---

flask_restplus/api.py

Original issue is #22. Fix in #23 was not complete.
Once `add_resource` is called, you cannot undo it and every next run of `init_app` with another Blueprint or Flask-app will inevitably augment them with `/swagger.json` endpoint even if `add_specs=False`. Even worse, if `init_app` is called with `add_specs=True` (default) the second time, it would fail as the specs resource was already added previously.
My fix is cleaner as it mounts specs resource straight to the Blueprint/Flask-app, just like `_register_doc` does.

Fixes #22: Exception is raised when init_app() is called more than once

---

flask_restplus/api.py

After code was added to forward HTTPException headers, the code to add
the 'Allow' headers for a 405 response became unnecessary. See the
following:
https://github.com/flask-restful/flask-restful/pull/523

Remove unnecessary 405 code

---

flask_restplus/api.py
tests/test_errors.py

Give user ability to pass headers from default or custom error handlers. There may be better ways to do this so I am open to suggestions. Perhaps using a more unique key like `__headers` or `__restplus_headers` as to avoid conflicting with anything. Another alternative I can think of is to make the exceptions return a third tuple value that contains the headers.

Add ability to pass headers from error handlers

---

flask_restplus/api.py

I was trying to debug why the Swagger UI wasn't making the browser prompt for basic authentication and eventually found the `serve_challenge_on_401` option which was added with the dropping of Flask-Restful as a requirement but it doesn't show up in the generated documentation. So here's a small PR that should add it and prevent anyone else scratching their head :smile:

Add documentation for serve_challenge_on_401

---

flask_restplus/templates/swagger-ui.html

This PR is related to issue #138.
You neeed to specify `app.config.SWAGGER_UI_OAUTH_CLIENT_ID` to enable OAuth support in Swagger-UI.
There are also two optional (though recommended) config options:
* `SWAGGER_UI_OAUTH_REALM`
* `SWAGGER_UI_OAUTH_APP_NAME`

Closes #138: Added new OAuth-related config options for Swagger-UI

---

doc/swagger.rst

Hi there,
I just started playing around with `flask-restplus`, and I'm really impressed with how easy it was to get set up!  The Swagger integration is a game-changer.
However, I noticed some typos and awkward phrasing in the `flask-restplus` documentation.  This is an attempt to make the docs a little more consistent and easier to read.
Please let me know if you'd like me to make any changes so this PR can get merged.
Thank you!
-- Will

Update Swagger documentation

---

doc/marshalling.rst

In "Custom fields" example, this 'all_caps_name' is an alias for attribute 'name', while I believe there should be quotation marks for the attribute.

Add quotation marks for attributes alias

---

flask_restplus/namespace.py

Please, notice that `http_method_funcs` include `TRACE` HTTP method which was not on the list previously, but it seems to be not a big deal.

Replaced hardcoded list of HTTP methods with `flask.views.http_method_funcs`

---

flask_restplus/api.py

Besides avoiding code duplication, it makes possible to override one method to replace `Namespace` class with user's implementation.

Use namespace factory for default namespace instead of code duplication

---

flask_restplus/model.py
tests/test_model.py
tests/test_swagger.py

Definitions not having types makes it so that clients such as bravado can't figure out how to unmarshall a response. This should fix that.
I'm not certain that it's required by the standard, but every example I could find contained it and we know that at least one client expects it.

model definitions should report their type

---

setup.py

It's hard to package eggs that drop tests everywhere.
https://pythonhosted.org/setuptools/setuptools.html#using-find-packages

Don't install tests by default

---

flask_restplus/reqparse.py
tests/test_reqparse.py

reqparse was missing the type `number` in `PY_TYPES` for the python type `float`.

reqparse was missing swagger type number for python type float

---

flask_restplus/api.py
flask_restplus/model.py
flask_restplus/resource.py
tests/test_model.py
tests/test_payload.py

The JSON Schema specification defines the optionally-supported 'format' keyword for semantic validation of string values. [[1]](http://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-7)
For example, given the following JSON schema:
```json
{
"type": "object",
"properties": {
"name": {"type": "string", "format": "ipv4"}
}
}
```
A JSON schema validator that does not conform to the 'format' keyword would render the JSON object `{"ip": "awesome-ip"}` valid, whereas one that conforms to it, would render it invalid.
Currently Flask-RESTPlus does not support the ability to add a semantic validator. With this patch, the Api constructor may receive a `jsonschema.FormatChecker` object as argument, that will be passed from the `resource.Resource.validate_payload` method to the …

Add semantic validation for input payload

---

doc/scaling.rst

I guess it made no sense to call init_app on a blueprint here

Calling init_app on blueprint fixed

---

doc/scaling.rst
flask_restplus/api.py
flask_restplus/namespace.py
flask_restplus/swagger.py
tests/test_api.py

Hello!
I very love your namespace objects, but it isn't flexible. I add support of bind custom prefix path in Api.add_namespace method.
Example of namespace file
```python
#mymodule.py
ns = restplus.Namespace('test_ns', description='Test namespace')
@ns.route('/test/', endpoint='test_resource')
class TestResource(restplus.Resource):
pass
```
And create application
```python
#app.py
import mymodule
app = flask.Flask(__name__)
api = restplus.Api(app)
api.add_namespace(mymodule.ns, '/api_test')
```
In result I bind `mymodule.ns` on prefix path `'/api_test'`. If you try generate url by `url_for('test_resource')`, then you will get url `/api_test/test/`.

Add custom paths for ns in apis

---

flask_restplus/postman.py
tests/test_postman.py

Having a resource with path "/resource/", when the api has the prefix "/api", resulted in the url "/ap/resource/" in postman doc (missing "i").
This change checks the slash existence before removing it.

Fix prefix trailing slash stripping in Postman doc generation

---

flask_restplus/api.py
flask_restplus/resource.py

It allows for custom Response classes inheriting from the BaseResponse only when you set `app.response_class`.

Test on BaseResponse instead of Response

---

flask_restplus/swagger.py
tests/test_swagger.py

Add support for optional type arguments in URLs e.g. string(length=2).

---

flask_restplus/swagger.py

It is useful for Swagger Codegen since most of the programming languages rely on the function parameters order.

Preserve order of parameters

---

flask_restplus/model.py
flask_restplus/representations.py
tests/test_model.py

Had to do some wierd stuff with `args` to get things to work with `OrderedDict`. Otherwise the `deepcopy()` in `resolved` would not work properly. Struggled finding a better way to do this but would love to hear any ideas.

Use OrderedDict for Models

---

flask_restplus/reqparse.py
tests/test_reqparse.py

Before the request parser from Flask-RESTful was brought into
Flask-RESTPlus a commit was made to format the help messages of a parser
argument when creating the error string. This doesn't really work that
well with Flask-RESTPlus since those help messages are also used in the
swagger documentation. If someone wanted to retain this same
functionality another argument property would likely be needed. This
reverts things to how they worked previous to the merger.

Fix error messages from reqparse

---

flask_restplus/swagger.py

Similar to pull request #248, but also preserves order of parameters when using RequestParser

Preserve order of parameters with RequestParser

---

CHANGELOG.rst
doc/marshalling.rst
flask_restplus/marshalling.py
tests/test_marshalling.py

You can skip those fields which values is `None` instead of marshaling those fields with JSON value, null.
This feature is useful to reduce the size of response when you have a lots of fields which value may be None, but which fields are `None` are unpredictable.

Add an optional key argument, skip_none, in `marshal_with` and `marshal`

---

CHANGELOG.rst
flask_restplus/mask.py

`six.text_type` in Python 2.7 is for unicode strings only. The fix makes it also work for standard Python 2.7 strings.

Fix str masks for marshalling is Python 2.7 (issue-217)

---

flask_restplus/_http.py
flask_restplus/api.py
flask_restplus/errors.py
flask_restplus/model.py
flask_restplus/namespace.py
flask_restplus/reqparse.py
flask_restplus/swagger.py
flask_restplus/utils.py
setup.py

This makes the code expressive and less error-prone.
P.S. It is part of my patchset from the [flask-restplus-server-example](https://github.com/frol/flask-restplus-server-example). I am going to PR marshmallow / webargs support next (#9).

Replaced all integer HTTP codes with HTTPStatus enum values

---

doc/marshalling.rst

While here, remove an extra space.

Use the function marshal() instead of the decorator @marshal_with().

---

doc/marshalling.rst
flask_restplus/fields.py
flask_restplus/marshalling.py
tasks.py
tests/test_fields.py
tests/test_marshalling.py

As @nicbou mentioned, previous PR #269 missing support `skip_none` for `fields.Nested`.
Implement the missing parts in this PR.

Add skip_none for fields.Nested

---

flask_restplus/namespace.py
flask_restplus/swagger.py
tests/test_swagger.py

Using `@Namespace.doc(produces=['application/octet-stream'])` decorator for a method, I can now document the mimetype of specific endpoints.

Added 'produces' section support for a specific method

---

tasks.py

The folder needs to be present before assets are moved there post `npm install`, otherwise the swaggerui files return 404 for the API documentation.

Added static folder in web assets task

---

doc/errors.rst
flask_restplus/api.py
tests/test_errors.py

Flask-RESTPlus will return a message in the error response by default, which works great in common scenarios. As a developer, if a custom response is required as an error, Flask-RESTPlus will include a message field in this error response. In some scenarios, including the message field is not ideal.
At the moment, it is not possible to exclude/remove the message field in the error response. To handle this requirement, a new configuration option has been added to not include message in the error response. 
To disable the default behaviour, set the ``ERROR_INCLUDE_MESSAGE``  setting to ``False`` in the application config.

Added configuration to not force message in error response

---

.eggs/README.txt
doc/errors.rst
flask_restplus/api.py
tests/test_errors.py

Flask errorhandler catches subtypes of exceptions.
The restplus version only catches explicit errors, so if you have 50 errors all of base class MyException you need 50 api.errorhandler() decorations.
Not one api.errorhandler(MyException)

Catch errors of child types

---

doc/errors.rst
flask_restplus/api.py
flask_restplus/inputs.py
tests/test_errors.py

Registration of error handlers on a namespace created using 
```
class CustomException(RuntimeError): pass
api = restplus.Api(app)
ns = api.namespace("ExceptionHandler", path="/")
@ns.errorhandler(CustomException)
def handle_custom_exception(error):
return {'message': str(error), 'test': 'value'}, 400
```
fail to be executed because the factory `api.namespace` adds error handlers immediately to `api.error_handlers`.
I made `api.error_handlers` an internal property and on read I enhance with error handlers from child namespaces. Suggestions are welcome.
Thanks for this great package!

API error handlers read from namespace's error handlers

---

LICENSE
package.json
setup.py

See discussion in #319. If code from Flask-RESTful remains, then it's not OK to relicense it under the MIT License.
Both are highly permissive licenses, so not much changes in practice!
Here are some nice summaries of both:
* [BSD 3-Clause](https://tldrlegal.com/license/bsd-3-clause-license-(revised))
* [MIT License](https://tldrlegal.com/license/mit-license)

Change license to BSD 3 Clause

---

requirements/install.pip
setup.py

https://www.python.org/dev/peps/pep-0508/#environment-markers
fix #443

use environment markers to specify enum34 requirement to fix pip install

---

doc/swagger.rst

params -> 'params'
It is a string not object

Fix typo in doc/swagger.rst

---

examples/todomvc.py

The `readonly` property had a typo, corrected that, so now the swagger UI displays the example API payload correctly (without the id field), as originally intended.

Todo model's id readonly property typo fix

---

flask_restplus/api.py

When `Api` is initialized without `app` and `init_app` is called before all the resources are registered, the resources end up to be 404 Not Found.
Consider the following code:
```python
api = Api(...)
app = Flask('app')
api.init_app(app)
ns = Namespace(...)
ns.route(...)
api.add_namespace(ns)
```
Without this fix, the `ns` routes end up to be not propagated to the Flask `app`, and thus the server responds with 404 Not Found.

Fix late resource (route) registration

---

flask_restplus/api.py
tests/test_errors.py

Propagate exceptions from the flask-restplus handler even if they come from a restplus resource (for example, if you decorate a restplus resource with Flask-JWT's @jwt_required, then restplus will catch it even if it shouldn't)

Propagate exceptions from the flask-restplus handler if propagate exceptions is enabled

---

flask_restplus/reqparse.py
flask_restplus/swagger.py

These changes avoid two warnings in python 3.7 similar to:
```
<venv>/lib/python3.7/site-packages/flask_restplus/swagger.py:8
<venv>/lib/python3.7/site-packages/flask_restplus/swagger.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Hashable
```
Ostensibly, flask_restplus will break in python 3.8. It will fall back to old-style imports.

-Fix ABC deprecations, targeted for removal in python 3.8

---

CHANGELOG.rst
flask_restplus/swagger.py
tests/test_swagger.py

Fixes #615
Namespaces where all Resources are hidden:
- Are not added to the Swagger `tags` property
- Are not shown in the Swagger UI
Example from #615:
```python
from flask import Flask
from flask_restplus import Api, Namespace, Resource
app = Flask(__name__)
api = Api(app)
namespace_with_resources = Namespace("Resources")
api.add_namespace(namespace_with_resources)
@namespace_with_resources.route("/foo", doc=False)
class MyResource(Resource):
def get(self):
return "foo"
namespace_without_resources = Namespace("No Resources")
api.add_namespace(namespace_without_resources)
if __name__ == "__main__":
app.run(port=8080)
```
Namespace without resources is no longer shown:

Hide Namespaces With All Hidden Resources

---

doc/swagger.rst
flask_restplus/templates/swagger-ui.html

Swagger UI by default provides a "Try it Out" button for all paths and methods. Some users have requested the ability to disable this feature for use in production environments - see issue #513.
- Support per-route/namespace/method toggle via `doc` decorator? For example
```python
@api.doc(try_it_out=False)
@ns.route('/')
class TodoList(Resource):
'''Shows a list of all todos, and lets you POST to add new tasks'''
def get(self):
'''List all tasks'''
return DAO.todos
def post(self):
'''Create a new task'''
return DAO.create(api.payload), 201
@ns.route('/<int:id>')
class Todo(Resource):
'''Show a single todo item and lets you delete them'''
@ns.doc('get_todo', try_it_out=False)
def get(self, id):
'''Fetch a given resource'''
return DAO.get(id)
def delete(self, id):
'''Delete a task given …
```

Toggle Swagger UI Try it Out Feature

---

doc/swagger.rst

#635 highlighted that the `oauth2` authorization example in the docs is missing a required `authorizationUrl` parameter - this was causing issues when using the Swagger UI authentication. It is also unclear from the docs exactly what options the `authorizations` configuration can contain
- Fix incorrect `oauth2` example
- Explain how the `authorizations` configuration maps directly to the Swagger [`securityDefinitions`](https://swagger.io/docs/specification/2-0/authentication/)  configuration

Improve Swagger Authorization Docs

---

doc/example.rst

Problem is here
https://flask-restplus.readthedocs.io/en/stable/example.html
As per documentation here 
https://flask-restplus.readthedocs.io/en/stable/api.html#flask_restplus.fields.Raw
The field is called `readonly`, not `readOnly`.
This fails silently, leading to long sessions of debugging.

Documentation: the parameter should be called readonly

---

CHANGELOG.rst
doc/swagger.rst
flask_restplus/api.py
flask_restplus/namespace.py
flask_restplus/swagger.py
tests/test_swagger.py

See #288 for initial issue. 
Using the `doc` parameter of `Api.route()` decorator applies documentation to the `Resource` as a whole. This prevents documentation being added on a per-route basis (for example adding an additional description to a route, or marking one route as deprecated) as the `doc` is applied to all routes.
Furthermore, each route uses the same Swagger `operationId`, causing both routes to be expanded at the same time when selecting one in the Swagger UI (the elements are selected using an HTML `id` which is set to the `operationId`.
- Using the `doc` parameter `Api.route()` will apply the documentation to that route only
- Routes using the `doc` parameter are given unique `operationId`s (combining the original `operationId` with the URLs provided)
- Each route will …

Multiple Routes Swagger Documentation 

---

doc/swagger.rst
flask_restplus/templates/swagger-ui.html
tasks.py

The swagger-ui project contains a 'oauth2-redirect.html' file
which provides a credential trampoline. Vendor it in, and
place the external url to this file in swagger-ui.html.
The OAuth2 authentication loop is run in a popup window/tab.
The IDP will redirect back to the oauth2RedirectUrl with an
access_token provided in the #hash-fragment of the url.
Javascript running inside 'oauth2-redirect.html' pushes the
access_token back to the parent which created the window/tab,
before closing the tab.
Enables use-case in #544 without adding another config param.
Usage:
```python
app.config.SWAGGER_UI_OAUTH_CLIENT_ID = 'MyClientId'
app.config.SWAGGER_UI_OAUTH_REALM = '-'
app.config.SWAGGER_UI_OAUTH_APP_NAME = 'Demo'
api = Api(
app,
title='Demo',
security={'OAuth2': ['read', 'write']}, …
```

Enable OAuth2 Implicit Flow authentication round-trip in Swagger UI

---

CHANGELOG.rst
flask_restplus/api.py
tests/test_errors.py

This PR changes the `Api.error_router` so that it does not suppress exceptions which are raised in the implementation of error handling functions associated with Apis or Namespaces. Currently, buggy error handler implementations are unnecessarily difficult to diagnose and fix because any exceptions raised (other than the original exception being handled by the error handler) are suppressed. They do not appear in the log output, and do not cause a 500 Internal Server Error when they should.
With this changes, such errors – which are usually programming errors – are properly logged and give an appropriate response.
This PR is a direct response to #705

Fix error handler exception suppression

---

flask_restplus/fields.py

Resolves `DeprecationWarning: The import 'werkzeug.cached_property' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.utils import cached_property' instead.` raised by Werkzeug 0.19+.
`cached_property` has always resided in werkzeug.utils, so this is backwards-compatible.

Update deprecated import for werkzeug's cached_property

---

CHANGELOG.rst
doc/marshalling.rst
doc/quickstart.rst
flask_restplus/api.py
flask_restplus/marshalling.py
flask_restplus/mask.py
flask_restplus/model.py
flask_restplus/schemas/__init__.py
flask_restplus/swagger.py
flask_restplus/utils.py
tests/test_fields.py
tests/test_fields_mask.py
tests/test_marshalling.py
tests/test_model.py

Import the ABCs from 'collections.abc' instead of 'collections' by default as it is deprecated since Python3.7, and in 3.8 it will stop working.
I considered that Python3 is the de-facto standard as Python2 support is being dropped in every other Python project and support ends at end of year. This is why I removed the OrderedDict sample and use a builtin dict instead of they are ordered since 3.6
I however kept Python2 support in the unlikely event that some projects are still upgrading flask-restplus dependency while not upgrading to Python3.
I did not add any additional test case as I assume the test suite runs with Python2 as well as 3.X, if this is not the case I am more than happy to remove the extra TODO and try/except blocks in this PR.
closes #727

Import the ABCs from 'collections.abc' instead of 'collections'

---

CHANGELOG.rst
flask_restplus/swagger.py
tests/test_swagger.py

Change to swagger.py in refs function, and a new test in tests_swagger.py.

Fix for issue #651

---

doc/index.rst
doc/logging.rst
flask_restplus/api.py
flask_restplus/namespace.py
tests/conftest.py
tests/legacy/test_api_legacy.py
tests/test_logging.py

Implements per Api/Namespace logging as discussed in https://github.com/noirbizarre/flask-restplus/issues/694

Implement Api/Namespace Loggers

---

flask_restplus/fields.py
tests/test_marshalling.py

This allows you to use `fields.Nested` or `fields.List` as Wildcard inner fields.

fix: make Wildcard fields support Nested and List fields (fix #728)

---

flask_restplus/api.py
tests/test_errors.py

If errorhandler is configured, error should not be returned to client
even if PROPAGATE_EXCEPTIONS is true.

Don't return exception when errorhandler is set (fix #693)

---

CHANGELOG.rst
flask_restplus/namespace.py
flask_restplus/swagger.py
tests/test_swagger.py

Fixes #390 
If `envelope` presents in `marshal_with` options response schema should have the following form:
```
{"properties": {envolope_key: response_model}}
```

Support envelope parameter in Swagger documentation #390

---

README.rst

Let the community know about the fork and give some context.
cc. @j5awry, @SteadBytes

explain about the fork

---

LICENSE

I, John Chittum, was the sole contributor from Akamai Technologies. However, my work on this project has been essentially administrative. I have not submitted any code changes to this codebase. My work relationship with Akamai Technologies ends on January 17th 2020. As such, Akamai being on the general license is unneeded. If other Akamai employess wish to contributor to this defunct codeline, please use a per commit style marking, stating copyright of the change is owned by Akamai Technologies.

Removing Akamai License. 
